src/Blanche/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Blanche import settings
from shop.views import index
from accounts.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("marketplace/", include("marketplace.urls")),
    path('profile/', profile, name='profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from .views import signup, user_logout, edit_profile, profile, PasswordReset, PasswordResetDone, PasswordResetConfirm, PasswordResetComplete
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('logout/', user_logout, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    # PASSWORD RESET
    path('password_reset/', PasswordReset.as_view(), name='password_reset',),
    path('password_reset/done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),

]

src/marketplace/urls.py
from django.urls import path

from shop.views import vitrine, create_vitrine, edit_vitrine, search_results, vitrine_detail, all_vitrines
from marketplace.views import create_marketplace, all_marketplace, CreateProduct,ProductDetail, add_to_cart, my_marketplace, cart_view,validate_cart_view,delete_product_from_cart, delete_cart



app_name = "marketplace"
urlpatterns = [


    #Search
    path('search/', search_results, name='search_results'),

    #Cart
    path("add_to_cart/<int:pk>/", add_to_cart, name="add_to_cart"),
    path("cart/", cart_view, name="cart"),
    path("validate_cart/", validate_cart_view, name="validate_cart"),
    path("delete_cart/<int:pk>", delete_cart, name="delete_cart"),



    #Marketplace
    path('all_marketplace/', all_marketplace, name='all_marketplace'),
    path("create_marketplace/", create_marketplace, name="create_marketplace"),
    path('my_marketplace/', my_marketplace, name='my_marketplace'),

    #Product
    path("create_product/", CreateProduct.as_view(), name="create"),
    path("delete_product/<int:pk>", delete_product_from_cart, name="delete_product"),
    path("<slug:slug>/", ProductDetail.as_view(), name="detail"),
]

src/shop/urls.py
from django.urls import path

from shop.views import vitrine, create_vitrine, edit_vitrine, search_results, vitrine_detail, all_vitrines
app_name = "shop"
urlpatterns = [

    path('vitrine/', vitrine, name='vitrine'),
    path('create_vitrine/', create_vitrine, name='create_vitrine'),
    path('no_vitrine/', create_vitrine, name='vitrine_non_cree'),
    path('edit_vitrine/', edit_vitrine, name='edit_vitrine'),
    path('search/', search_results, name='search_results'),
    path('vitrine/<slug:slug_vitrine>/', vitrine_detail, name='vitrine_detail'),
    path('all_vitrines/', all_vitrines, name='all_vitrines'),
    path('vitrine/<slug:slug_vitrine>/user/<int:user_id>/', vitrine_detail, name='vitrine_detail'),
    path('vitrine/user/<int:user_id>/', vitrine_detail, name='vitrine_detail'),

]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'index' %}">La Marmite Digitale</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-nowrap" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:logout' %}">Déconnexion</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:signup' %}">Inscription</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:login' %}">Connexion</a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown2" href="#" role="button"
                           data-bs-toggle="dropdown">Mon compte</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profil</a></li>
                            <li><hr class="dropdown-divider"/></li>
                            {% if user_profile.role == 'vendeur' %}
                                <li><a class="dropdown-item" href="{% url 'marketplace:create' %}">Mettre en vente</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="#">Mes commandes / ventes</a></li>
                        </ul>
                    </li>
                {% endif %}
                <li class="nav-item"><a class="nav-link active" href="{% url 'shop:all_vitrines' %}">Les Vitrines</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'marketplace:all_marketplace' %}">La Marketplace</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown3" href="#" role="button"
                       data-bs-toggle="dropdown">Assistance</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Chat</a></li>
                        <li><hr class="dropdown-divider"/></li>
                        <li><a class="dropdown-item" href="#">F.A.Q</a></li>
                        <li><a class="dropdown-item" href="#">Historique</a></li>
                    </ul>
                </li>
                {% if user_profile and user_profile.role == 'gestionnaire' %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'admin:index' %}">Administration</a>
                    </li>
                {% endif %}
                {% if user_profile and user_profile.role == 'vendeur' %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'shop:vitrine' %}">Ma vitrine</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'marketplace:my_marketplace'%}">Ma marketplace</a></li>
                {% endif %}
            </ul>

            <!-- Formulaire de recherche -->
            <form class="d-flex me-2" action="{% url 'shop:search_results' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Rechercher..." aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Rechercher</button>
            </form>

            <!-- Panier -->
            <a href="{% url 'marketplace:cart' %}" class="btn btn-outline-dark">
                <i class="bi-cart-fill me-1"></i>
                Panier
                <span class="badge bg-dark text-white ms-1 rounded-pill">
                    {% if request.user.cart %}{{ request.user.cart.orders.all.count }}{% else %}0{% endif %}
                </span>
            </a>
        </div>
    </div>
</nav>

<!-- Header -->
<header class="bg-light bg-gradient py-5 border border-secondary">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-black">
            <h1 class="display-4 fw-bolder">La Marmite Digitale</h1>
            <p class="lead fw-normal text-black-50 mb-0">Marketplace pour vos vêtements</p>
        </div>
    </div>
</header>

<!-- Section principale -->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        {% block body %}{% endblock %}
    </div>
</section>

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; La Marmite Digitale 2024</p></div>
</footer>

<!-- Bootstrap core JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS -->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

src/templates/test.html
{% extends "base.html" %}
{% block title %}La Marmite Digitale{% end block %}

{% block body %}
<h1 class="display-4 fw-bolder">youhouuoouu</h1>

{% end block %}